// <auto-generated />
namespace Demo1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddGrossRevenueToManufacturer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGrossRevenueToManufacturer));
        
        string IMigrationMetadata.Id
        {
            get { return "201212022159573_AddGrossRevenueToManufacturer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
